### ISSUE TITLE
Re-desing RI and RIi

### ISSUE THREAD

**Issue by pathumego** [mooniak/gemunu-libre-font#10]
It feels like a blob. @kosalaya 
<img width="186" alt="screen shot 2016-02-16 at 9 45 16 am" src="https://cloud.githubusercontent.com/assets/6846609/13072578/1552fe28-d492-11e5-8601-ff1f07ed931d.png">

**Comment by kosalaya** [comment]
<img width="243" alt="screen shot 2016-02-20 at 1 15 38 am" src="https://cloud.githubusercontent.com/assets/8073976/13187151/9755d78a-d76f-11e5-8b37-8533c246fe67.png">
<img width="264" alt="screen shot 2016-02-20 at 1 15 58 am" src="https://cloud.githubusercontent.com/assets/8073976/13187152/9761863e-d76f-11e5-8eb2-2610844428ce.png">
share your comments on these two. @pathumego

**Comment by pathumego** [comment]
ok im not totally convinced. Can we try changing the base glyphs a bit too?

**Comment by kosalaya** [comment]
<img width="407" alt="screen shot 2016-02-22 at 3 43 53 pm" src="https://cloud.githubusercontent.com/assets/8073976/13215426/33f4d1ba-d97b-11e5-9cb4-88f0cbec6596.png">
<img width="384" alt="screen shot 2016-02-22 at 3 44 06 pm" src="https://cloud.githubusercontent.com/assets/8073976/13215425/33e0344e-d97b-11e5-9e38-0276ae9e0d7b.png">
any suggesions to improve these?
