### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by alexmyczko** [mooniak/gemunu-libre-font#17]
isn't there a way to build it on linux without vagrant?

**Comment by pathumego** [comment]
Yep. Vagrant essntially packs the build dependencies and installs them. You can see what you need to install here https://github.com/mooniak/gemunu-libre-font/blob/master/scripts/bootstrap.sh

**Comment by alexmyczko** [comment]
Ok that's a first. I want to create official Debian packages of it, (and Ubuntu will copy them). So, here's a start:

Downloads during building is not allowed.

http://phd-sid.ethz.ch/debian/fonts-gemunu-libre/

So just fontforge-nox, or fontmake, or ufo2otf alone won't do it?

**Comment by pathumego** [comment]
Nope, there is some ufo conversion and merging happening with current build. TBH it is a overkill. we are building using AFDKO with a light wrapper. I already moved some of our other projects to fontmake only build. I will get this one in Jan or so.

PS:
@alexmyczko thanks a bunch! We've been looking for help with packaging for Debian.

**Comment by alexmyczko** [comment]
Sounds good, if we can make it build with free tools, until early January 2019, we can make it into the next debian stable release, and Ubuntu 19.04...

**Comment by alexmyczko** [comment]
Do you think something will happen during the next few days?

**Comment by pathumego** [comment]
Sorry. No I will get this working by end of next week. I have everything
working on Abhay Libre repo. Need setup this repo.

**Comment by alexmyczko** [comment]
If you get it working by next week Saturday, chances are with urgency=high and super fast ftp master it might get into buster, maybe

**Comment by alexmyczko** [comment]
ping any news?

**Comment by pathumego** [comment]
Hi @alexmyczko I will attned to this in March first week. Apologies about the delays.

**Comment by alexmyczko** [comment]
Any luck?

**Comment by alexmyczko** [comment]
https://github.com/googlefonts/fontmake/issues/583

**Comment by alexmyczko** [comment]
meanwhile i was able to load and export the .glyphs on macos with glyphsapp, generated ufo files build fine with fontmake
