### ISSUE TITLE
Interpolation errors

### ISSUE THREAD

**Issue by paarandika** [mooniak/gemunu-libre-font#7]
vocalicR    - wrong direction / extra points
vocalicRr   -   “     “
vocalic LL  - number of contours 
Kha     - extra points
Ga      - wrong direction
Nga     -   “
Ca      - contour order
Ja      - extra points
Jha     - contour order / starting point
Nya     - extra points
Ndja        - Ja incomple
Ddha        - starting point
Pa      - extra points
Pha     - contour order
Ba      -   “
Ma      -   “
Mba
Ra
Ssa
Sa
Lla
Kundaliya

**Comment by paarandika** [comment]
These error are propagated to other glyphs via references.

**Comment by pathumego** [comment]
@kosalaya seems there are lot of glyphs missing in the built files stiil. I checked for interpolation seems like all interpolation errors.

**Comment by pathumego** [comment]
@kosalaya These still fail

```
si_GhR.halant
si_JR.halant
si_Ya.post.MatraI
si_Ya.post.MatraIi
si_HRI
```
