### ISSUE TITLE
Feature not working

### ISSUE THREAD

**Issue by pathumego** [mooniak/gemunu-libre-font#9]
The wholw R.halant is not working
<img width="162" alt="screen shot 2016-02-15 at 10 16 37 pm" src="https://cloud.githubusercontent.com/assets/6846609/13061757/d6c7d2b0-d431-11e5-9ff2-b69df5f7f73b.png">

**Comment by paarandika** [comment]
Those are the missing glyphs I mentioned.

**Comment by pathumego** [comment]
Glyphs added by Kosala

On Tue, Feb 16, 2016, 8:12 AM Ayantha Randika notifications@github.com
wrote:

> Those are the missing glyphs I mentioned.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mooniak/gemunu-libre-font/issues/9#issuecomment-184569359
> .
> 
> ## 

෴ ජය! ෴
පැතුම් එගොඩවත්ත
Pathum Egodawatta
pathum@mooniak.com

**Comment by paarandika** [comment]
fixed
